"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "$all"

[character]
success_symbol = "[âœ ](purple)"
error_symbol = "[âœ ](red)"
vicmd_symbol = "[âœ ](green)"

[directory]
read_only = " ó°Œ¾"
truncation_length = 4
truncation_symbol = '~/'
style = "bold bright-cyan"

[c]
symbol = "î˜  "
format = 'via [$symbol($version(-$name) )]($style)'
commands = [ [ 'clang', '--version' ] ]

[cmake]
symbol = "î” "

[git_branch]
symbol = "ï˜ "

[git_commit]
tag_symbol = ' ï’ '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
staged = '[++\($count\)](green)'
style = "bold bright-purple"

[fossil_branch]
symbol = "ï˜ "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[java]
symbol = "î‰– "

[memory_usage]
symbol = "ó°› "

[package]
symbol = "ó°— "

[python]
symbol = "îˆµ  "

[nodejs]
symbol = "îœ˜ "

[os]
disabled = false

[os.symbols]
Debian = "ïŒ†  "

[rust]
symbol = "î¨ "

[sudo]
symbol = 'ğŸ‘©â€ğŸ’» '
style = 'bold bright-blue'
disabled = false

[gradle]
symbol = "î™  "

[jobs]
symbol = "ï€“"
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
style = "bold bright-yellow"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
